version: '3.9'

services:
  master1:
    build: .
    container_name: master1
    hostname: master1
    ports:
      - "9870:9870"
      - "9000:9000"
      - "2181:2181"
    environment:
      - HADOOP_NODENAME=nn1
    volumes:
      - hadoop_data_master1:/opt/hadoop/hdfs
    networks:
      hadoop_net:
        ipv4_address: 172.19.0.2
    healthcheck:
      test: ["CMD", "jps"]
      interval: 20s
      timeout: 10s
      retries: 5

  master2:
    build: .
    container_name: master2
    hostname: master2
    ports:
      - "9871:9870"
      - "2182:2181"
    environment:
      - HADOOP_NODENAME=nn2
    volumes:
      - hadoop_data_master2:/opt/hadoop/hdfs
    networks:
      hadoop_net:
        ipv4_address: 172.19.0.3
    depends_on:
      - master1
    healthcheck:
      test: ["CMD", "jps"]
      interval: 20s
      timeout: 10s
      retries: 5

  master3:
    build: .
    container_name: master3
    hostname: master3
    ports:
      - "9872:9870"
      - "2183:2181"
    environment:
      - HADOOP_NODENAME=nn3
    volumes:
      - hadoop_data_master3:/opt/hadoop/hdfs
    networks:
      hadoop_net:
        ipv4_address: 172.19.0.4
    depends_on:
      - master1
    healthcheck:
      test: ["CMD", "jps"]
      interval: 20s
      timeout: 10s
      retries: 5

  worker1:
    build: .
    container_name: worker1
    hostname: worker1
    volumes:
      - hadoop_data_worker:/opt/hadoop/hdfs
    networks:
      hadoop_net:
        ipv4_address: 172.19.0.5
    depends_on:
      - master1

volumes:
  hadoop_data_master1:
  hadoop_data_master2:
  hadoop_data_master3:
  hadoop_data_worker:

networks:
  hadoop_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16