services:
  master11:
    build: .
    container_name: master11
    hostname: master11
    ports:
      - "19870:9870"    # NameNode Web UI (original: 9870)
      - "18088:8088"    # ResourceManager Web UI (original: 8088)
      - "12181:2181"    # ZooKeeper (original: 2181)
      - "19000:9000"    # NameNode (original: 9000)
    environment:
      - HADOOP_NODENAME=nn1
    volumes:
      - hadoop_data_master11:/opt/hadoop/hdfs
    networks:
      hadoop_net:
    healthcheck:
      test: ["CMD", "jps"]
      interval: 20s
      timeout: 10s
      retries: 5

  master22:
    build: .
    container_name: master22
    hostname: master22
    ports:
      - "19871:9870"    # NameNode Web UI (original: 9871:9870)
      - "18089:8088"    # ResourceManager Web UI (original: 8089:8088)
      - "12182:2181"    # ZooKeeper (original: 2182:2181)
      - "19001:9000"    # NameNode (original: 9001:9000)
    environment:
      - HADOOP_NODENAME=nn2
    volumes:
      - hadoop_data_master22:/opt/hadoop/hdfs
    networks:
      hadoop_net:
    depends_on:
      - master11
    healthcheck:
      test: ["CMD", "jps"]
      interval: 20s
      timeout: 10s
      retries: 5

  master33:
    build: .
    container_name: master33
    hostname: master33
    ports:
      - "19872:9870"    # NameNode Web UI (original: 9872:9870)
      - "18090:8088"    # ResourceManager Web UI (original: 8090:8088)
      - "12183:2181"    # ZooKeeper (original: 2183:2181)
      - "19002:9000"    # NameNode (original: 9002:9000)
    environment:
      - HADOOP_NODENAME=nn3
    volumes:
      - hadoop_data_master33:/opt/hadoop/hdfs
    networks:
      hadoop_net:
    depends_on:
      - master11
    healthcheck:
      test: ["CMD", "jps"]
      interval: 20s
      timeout: 10s
      retries: 5

  worker11:
    build: .
    container_name: worker11
    hostname: worker11
    ports:
      - "19864:9864"    # DataNode Web UI (original: 9864)
    volumes:
      - hadoop_data_worker1:/opt/hadoop/hdfs
    networks:
      hadoop_net:
    depends_on:
      - master11

volumes:
  hadoop_data_master11:
  hadoop_data_master22:
  hadoop_data_master33:
  hadoop_data_worker1:

networks:
  hadoop_net:
    driver: bridge