FROM ubuntu:22.04

ENV HADOOP_VERSION=3.3.6 \
    ZOOKEEPER_VERSION=3.8.4 \
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
    HADOOP_HOME=/opt/hadoop \
    ZOOKEEPER_HOME=/opt/zookeeper \
    HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop \
    PATH=$PATH:/opt/hadoop/bin:/opt/hadoop/sbin:/opt/zookeeper/bin


RUN apt update
RUN apt install openjdk-8-jdk -y
RUN apt install ssh wget nano -y
RUN apt install netcat -y 
RUN apt install net-tools -y
RUN apt install sudo -y


RUN addgroup hadoop
RUN adduser --disabled-password --ingroup hadoop hadoop

ADD https://dlcdn.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz /tmp/hadoop.tar.gz
RUN tar -xzvf /tmp/hadoop.tar.gz -C /opt && \
    mv /opt/hadoop-${HADOOP_VERSION} /opt/hadoop && \
    rm /tmp/hadoop.tar.gz
RUN chown -R hadoop:hadoop /opt/hadoop


ADD https://dlcdn.apache.org/zookeeper/zookeeper-${ZOOKEEPER_VERSION}/apache-zookeeper-${ZOOKEEPER_VERSION}-bin.tar.gz /tmp/zookeeper.tar.gz
RUN tar -xzvf /tmp/zookeeper.tar.gz -C /opt && \
    mv /opt/apache-zookeeper-${ZOOKEEPER_VERSION}-bin /opt/zookeeper && \
    cp /opt/zookeeper/conf/zoo_sample.cfg /opt/zookeeper/conf/zoo.cfg && \
    rm /tmp/zookeeper.tar.gz
RUN chown -R hadoop:hadoop /opt/zookeeper

RUN echo "hadoop ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER hadoop
WORKDIR /home/hadoop

RUN ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa
RUN cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
RUN chmod 600 ~/.ssh/authorized_keys


RUN touch /opt/zookeeper/conf/zoo.cfg
RUN mkdir /opt/hadoop/tmp
RUN mkdir /opt/hadoop/hdfs
RUN mkdir /opt/hadoop/hdfs/namenode
RUN mkdir /opt/hadoop/hdfs/journal
RUN mkdir /opt/hadoop/hdfs/datanode

COPY core-site.xml $HADOOP_CONF_DIR/core-site.xml
COPY hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml
COPY yarn-site.xml $HADOOP_CONF_DIR/yarn-site.xml
COPY mapred-site.xml $HADOOP_CONF_DIR/mapred-site.xml
COPY hadoop-env.sh $HADOOP_CONF_DIR/hadoop-env.sh
COPY zoo.cfg /opt/zookeeper/conf/zoo.cfg
COPY workers /opt/hadoop/etc/hadoop/workers


COPY entrypoint.sh /home/hadoop/entrypoint.sh
RUN sudo chmod +x /home/hadoop/entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]